### ISSUE TITLE
AttributeError: module 'hid' has no attribute 'device'

### ISSUE THREAD

**Issue by leitao** [micolous/pcprox#1]
When I try to run it on my env, I get the following error. I am wondering if I am using the wrong hid library version (1.0.2), since it contains Device() but no device().
```
Traceback (most recent call last):
  File "configure.py", line 101, in <module>
    main(options.set_true, options.set_false, options.set_int, options.write_eeprom, options.debug)
  File "configure.py", line 38, in main
    dev = pcprox.open_pcprox(debug=debug)
  File "/home/root/py/pcprox.py", line 109, in open_pcprox
    dev = hid.device()
AttributeError: module 'hid' has no attribute 'device'
```

**Comment by soorajvnair** [comment]
Hey @leitao make sure you're running the program as root. sudo python3 configure.py and you should see it working normally. Also make sure you've installed all dependencies, like hidapi.

**Comment by MiguelAPerez** [comment]
@soorajvnair @leitao, I had to the same issue and I found changing _line 137_ on pcprox.py from **hid.device()** to **hid.Device(vid=PCPROX_VENDOR, pid=PCPROX_PRODUCT)**. The hid library doesn't have the device function then I just commented on line _329_. Hid also doesn't have the set_nonblocking anymore. If you're on Linux you can check the python dir -> /dist-packages/hid/\__init\__.py to see the functions. Lastly remove dev.open(PCPROX_VENDOR, PCPROX_PRODUCT) on line 138 (pcprox.py)

**Comment by micolous** [comment]
I think you have the wrong HID library.  Unfortunately, there are many identically named `hid` modules on PyPI.

[The set_nonblocking method is definitely there](https://github.com/trezor/cython-hidapi/blob/5d04e0cd359276eb9dde52b721a8a5fc5f637251/hid.pyx#L97).
