### ISSUE TITLE
Consider mentioning the two hidapi libraries in the README

### ISSUE THREAD

**Issue by hackerb9** [micolous/pcprox#3]
Debian and Ubuntu provide a package called `python3-hidapi` which provides hidapi.py from hidapi-cffi. However, pcprox requires hid.py from cython-hidapi. 

For Debian and descendants, one would do: `apt install python3-hid`.

**Comment by micolous** [comment]
Thanks!

I think I was referencing Alpine when I wrote this; they packaged this as https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-hidapi
